inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3 # same as .github/workflows/main.yml
  Exclude:
    - 'bin/*'
    - 'config/locales/*'
    - 'gemfiles/*'
    - 'lib/tasks/*'
    - 'vendor/bundle/**/*'
  NewCops: enable

plugins:
  - rubocop-performance

# ==============================================================================
# Cops

# Style cops

Style/Documentation:
  Enabled: false

# Metrics cops

Metrics/AbcSize:
  Severity: warning

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - test/**/*


Rails/AssertNot:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
