name: CI
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # same as .rubocop.yml, recommended Rails & Ruby version for Gemfile
          bundler-cache: true

      - name: Run linters
        run: |
          bundle exec rubocop --parallel

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        gemfile:
          - rails_7_0
          - rails_7_1
          - rails_7_2
          - rails_8_0
          - rails_next
        image_processor:
          - vips
          - mini_magick
        exclude:
          - ruby: '3.1'
            gemfile: rails_8_0
          - ruby: '3.1'
            gemfile: rails_next
          - ruby: '3.3'
            gemfile: rails_7_0
          - ruby: '3.4'
            gemfile: rails_7_0
          - ruby: '3.4'
            gemfile: rails_7_1
          - ruby: '3.4'
            gemfile: rails_7_2
        include:
          - ruby: '3.0'
            gemfile: rails_6_1_4
            image_processor: vips
          - ruby: '3.0'
            gemfile: rails_6_1_4
            image_processor: mini_magick
    steps:
      - name: Install imagemagick
        uses: mfinelli/setup-imagemagick@v6
        with:
          cache: true

      - name: Verify imagemagick
        run: magick -version

      - name: Install libvips
        run: sudo apt-get update && sudo apt-get -y install libvips

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get -y install ffmpeg

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set BUNDLE_GEMFILE
        run: echo 'BUNDLE_GEMFILE=${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile' >> $GITHUB_ENV

      - name: Set IMAGE_PROCESSOR
        run: echo 'IMAGE_PROCESSOR=${{ matrix.image_processor }}' >> $GITHUB_ENV

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
